version: '3.1'

services:
 db:
  image: postgres
  container_name: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: ${DB_PASSWORD}
   POSTGRES_USER: ${DB_USER}
   POSTGRES_DB: ${DB_NAME}
  ports:
   - '${DB_PORT}:5432'
  networks:
   - nest
  volumes:
   - postgres:/var/lib/postgresql/data

 server:
  container_name: nestjs
  image: nestjs-dev
  restart: unless-stopped
  build:
   context: ./
   dockerfile: ./server/Dockerfile
  volumes:
   - ./server:/app
  environment:
   DATABASE_URL: ${DATABASE_URL}
  ports:
   - '8000:8000'
  networks:
   - nest
  depends_on:
   - db

 client:
  container_name: nextjs
  restart: unless-stopped
  build:
   context: ./
   dockerfile: ./client/Dockerfile
  volumes:
   - ./client:/app
  ports:
   - '3000:3000'
  networks:
   - nest
  depends_on:
   - server

networks:
 nest:

volumes:
 postgres:
