version: '3.1'

services:
 db:
  image: postgres
  container_name: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: ${DB_PASSWORD}
   POSTGRES_USER: ${DB_USER}
   POSTGRES_DB: ${DB_NAME}
  ports:
   - '${DB_PORT}:5432'
  networks:
   - nest
  volumes:
   - postgres:/var/lib/postgresql/data

 server:
  container_name: nestjs
  image: nestjs-dev
  restart: unless-stopped
  build:
   context: ./server
   dockerfile: Dockerfile
  volumes:
   - ./server:/app
  environment:
   - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
  ports:
   - '8000:8000'
  networks:
   - nest
  depends_on:
   - db

networks:
 nest:

volumes:
 postgres:
