import type { Metadata } from 'next'
import Navigation from '@/components/navigation/Navigation'
import { PropsWithChildren } from 'react'
import Providers from '@/components/providers/Providers'
import Wrapper from '@/components/layout/Wrapper'
import localFont from 'next/font/local'

const avenirRoman = localFont({
	src: '../../fonts/AvenirLTStd-Roman.otf',
	variable: '--avenir-roman',
	display: 'swap',
})

const avenirBlack = localFont({
	src: '../../fonts/AvenirLTStd-Black.otf',
	variable: '--avenir-black',
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='en' className={`${avenirRoman.variable} ${avenirBlack.variable}`}>
			<head>
				<link rel='icon' href='/img/favicon.ico' sizes='any' />
			</head>
			<body>
				<Providers>
					<Wrapper>
						<Navigation />
						{children}
					</Wrapper>
				</Providers>
			</body>
		</html>
	)
}
