name: Client CI

on:
 push:
  branches:
   - master
  paths:
   - 'client/**'
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest

  defaults:
   run:
    working-directory: ./client

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up Node.js
     uses: actions/setup-node@v2
     with:
      node-version: 20.2.0

   - name: Install Dependencies
     run: yarn install

   - name: Start Next.js Application
     run: yarn run dev &

   - name: Wait for Next.js to start
     run: sleep 5s

   - name: Run TypeScript Type Check
     run: yarn type-check

   - name: Run Cypress Tests
     run: yarn cypress:run
