name: Cypress E2E Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install

      - name: Start Next.js Application
        run: yarn run dev &

      - name: Wait for Next.js to start
        run: sleep 15s

      - name: Run Cypress Tests
        run: yarn cypress:run

