name: Server CI

on:
 push:
  branches:
   - master
  paths:
   - 'server/**'

jobs:
 build:
  runs-on: ubuntu-latest

  defaults:
   run:
    working-directory: ./server

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Setup Node.js
     uses: actions/setup-node@v2
     with:
      node-version: 20

   - name: Install Dependencies
     run: yarn install

   - name: Run TypeScript Type Check
     run: yarn type-check

   - name: Unit Test
     run: yarn test

   - name: E2E Test
     run: yarn test:e2e
